import pandas as pd


alpha_metrics_path = "config/alpha_div_metrics.tsv"
alpha_metrics = pd.read_table(alpha_metrics_path, sep="\t")

beta_metrics_path = "config/beta_div_metrics.tsv"
beta_metrics = pd.read_table(beta_metrics_path, sep="\t")

non_phylo_alpha_metrics = alpha_metrics.query("phylogenetic == 'non_phylo'")["diversity_metric"]
phylo_alpha_metrics = alpha_metrics.query("phylogenetic == 'phylo'")["diversity_metric"]

non_phylo_beta_metrics = beta_metrics.query("phylogenetic == 'non_phylo'")["diversity_metric"]
phylo_beta_metrics = beta_metrics.query("phylogenetic == 'phylo'")["diversity_metric"]

rule all:
    input:
        "results/beta_div/effect_size_plot.html",
        "results/alpha_div/effect_size_plot.html"

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/preprocess_data.smk"
include: "rules/alpha_diversity.smk"
include: "rules/beta_diversity.smk"
include: "rules/evident.smk"
include: "rules/visualization.smk"
