feature_table_file: {{cookiecutter.sample_metadata_file}}
sample_metadata_file: {{cookiecutter.feature_table_file}}
max_category_levels: {{cookiecutter.max_category_levels}}
min_level_count: {{cookiecutter.min_level_count}}
rarefaction_depth_percentile: {{cookiecutter.rarefaction_depth_percentile}}
n_components: 3
