channels:
    - conda-forge
    - bioconda
dependencies:
    - pandas>=1.0.0
    - numpy
    - scikit-bio=0.5.6
    - h5py=3.1.0
    - biom-format
    - bokeh
    - unifrac>=1.0.0
    - unifrac-binaries>=1.0.0
    - seaborn=0.11.2
    - pip
    - pip:
        - gemelli>=0.0.8
        - evident>=0.4.0
