name: "Main CI"

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: xebec
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}

      # https://github.com/h5py/h5py/issues/1880
      - name: Install conda packages
        shell: bash -l {0}
        run: mamba install -c conda-forge -c bioconda biom-format h5py==3.1.0 scipy==1.8 numpy==1.23 snakemake pandas unifrac scikit-bio bokeh unifrac-binaries jinja2

      - name: Install pip packages
        shell: bash -l {0}
        run: pip install gemelli evident

      - name: Install xebec
        shell: bash -l {0}
        run: pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: make test

      - name: Run Snakemake
        shell: bash -l {0}
        run: make snaketest
